[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["hrntsm <contact@hrntsm.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.74"
